# Generated by Django 6.0.3 on 2026-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_paths', models.JSONField(blank=True, default=list, help_text='List of folder paths to exclusively sync')),
                ('exclude_paths', models.JSONField(blank=True, default=list, help_text='List of folder paths to explicitly ignore')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
