# Generated by Django 6.0.3 on 2026-04-18 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('note_type', models.CharField(choices=[('FLT', 'Fleeting Note'), ('REF', 'Reference Note'), ('PRM', 'Permanent Note')], default='FLT', max_length=3)),
                ('content_raw', models.TextField()),
                ('content_html', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('zettel_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.note')),
                ('is_atomic', models.BooleanField(default=True)),
                ('parent_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='notes.permanentnote')),
            ],
            bases=('notes.note',),
        ),
        migrations.CreateModel(
            name='ReferenceNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.note')),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('reference_type', models.CharField(help_text='Book, Article, Video vb.', max_length=50)),
            ],
            bases=('notes.note',),
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('REF', 'General Reference'), ('SEQ', 'Sequence (Folgezettel)'), ('STR', 'Structure (MOC)')], default='REF', max_length=3)),
                ('target_block', models.CharField(blank=True, max_length=255, null=True)),
                ('context_text', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='notes.note')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='notes.note')),
            ],
            options={
                'unique_together': {('source', 'target', 'target_block')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notes.tag')),
            ],
            options={
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='notes.tag'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
