# Generated by Django 6.0.3 on 2026-04-18 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referencenote',
            name='reference_url',
            field=models.CharField(blank=True, help_text='External URL or internal wikilink like [[Book Note]]', max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
