# Generated by Django 6.0.3 on 2026-04-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_published_referencenote_reference_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='toc',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
