# Generated by Django 6.0.3 on 2026-04-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
